import Foundation

struct MeasurementAtlasEntry: Identifiable, Hashable {
    var id: CanonicalChannel { channel }
    let channel: CanonicalChannel
    let title: String
    let purpose: String
    let diagnosticUse: String
    let relatedInvestigations: [String]
    let qualityNote: String
}

enum MeasurementAtlas {
    static func entry(for channel: CanonicalChannel) -> MeasurementAtlasEntry? { entries.first { $0.channel == channel } }

    static let entries: [MeasurementAtlasEntry] = [
        .init(channel: .engineRPM, title: "Engine RPM", purpose: "Operating-speed context for every transient.", diagnosticUse: "Correlate protection, injection-window, shift and thermal behavior to engine speed.", relatedInvestigations: ["R04 Fuel Capability", "Knock", "Fuel Pressure", "Lambda", "Throttle Closure"], qualityNote: "Preserve timestamp alignment; fast transients require adequate effective sample rate."),
        .init(channel: .injectorPulseWidth, title: "Actual Injector Pulse Width", purpose: "Delivered/requested injector on-time as represented by the logged parameter.", diagnosticUse: "Compare with maximum available PW to quantify remaining injection-window margin.", relatedInvestigations: ["R04 Fuel Capability", "Lambda Deviation"], qualityNote: "Parameter identity and units must be verified for the scanner/controller strategy."),
        .init(channel: .maximumInjectorPulseWidth, title: "Maximum Available Injector PW", purpose: "Available pulse-width envelope represented by the logged strategy parameter.", diagnosticUse: "Primary discriminator for injection-window limitation when compared with actual PW.", relatedInvestigations: ["R04 Fuel Capability"], qualityNote: "Treat identity as strategy-specific until the source parameter is verified."),
        .init(channel: .fuelPressureCommanded, title: "Commanded Fuel Pressure", purpose: "Controller pressure target.", diagnosticUse: "Pair with actual pressure to calculate tracking error and distinguish pressure delivery from other fuel limits.", relatedInvestigations: ["R04 Fuel Capability", "Fuel Pressure Tracking", "Lambda Deviation"], qualityNote: "Command and actual must use compatible units and time alignment."),
        .init(channel: .fuelPressureActual, title: "Actual Fuel Pressure", purpose: "Measured/reported fuel pressure.", diagnosticUse: "Quantify pressure error, onset, peak deviation and recovery.", relatedInvestigations: ["R04 Fuel Capability", "Fuel Pressure Tracking", "Lambda Deviation"], qualityNote: "Verify sensor/parameter identity before treating the value as a physical rail measurement."),
        .init(channel: .lambdaCommanded, title: "Commanded Lambda", purpose: "Controller mixture target.", diagnosticUse: "Pair with measured lambda to calculate tracking error during an event.", relatedInvestigations: ["R04 Fuel Capability", "Lambda Deviation"], qualityNote: "Do not compare channels with incompatible equivalence-ratio/AFR transforms."),
        .init(channel: .lambdaMeasured, title: "Measured Lambda", purpose: "Observed mixture response.", diagnosticUse: "Identify transient or sustained departure from command and correlate it with pressure/PW behavior.", relatedInvestigations: ["R04 Fuel Capability", "Lambda Deviation"], qualityNote: "Sensor latency and sampling rate matter during short events."),
        .init(channel: .gearActual, title: "Actual Gear", purpose: "Transmission state context.", diagnosticUse: "Locate shift episodes and calculate event timing relative to DCT transitions.", relatedInvestigations: ["R04 Fuel Capability", "Unexpected Throttle Closure"], qualityNote: "State transitions should be treated as episodes rather than independent samples."),
        .init(channel: .torqueProtectionSource, title: "Torque / Protection Source", purpose: "Controller ownership/state context for intervention.", diagnosticUse: "Correlate protection-source changes with fuel, throttle, spark and shift behavior.", relatedInvestigations: ["R04 Fuel Capability", "Unexpected Throttle Closure"], qualityNote: "Enum meanings can be strategy-specific and require source verification."),
        .init(channel: .knockRetard, title: "Knock Retard", purpose: "Logged spark-retard response associated with knock control.", diagnosticUse: "Bound knock episodes and compare against temperature, load and spark-source state.", relatedInvestigations: ["Knock / Spark Retard"], qualityNote: "Cylinder-specific and aggregate parameters must not be silently conflated."),
        .init(channel: .iat2, title: "IAT2 / Charge-Air Temperature", purpose: "Charge-air thermal context.", diagnosticUse: "Correlate thermal condition with knock, repeatability and protection behavior.", relatedInvestigations: ["Knock / Spark Retard", "R04 Fuel Capability"], qualityNote: "Verify sensor location/parameter semantics and units for the source configuration."),
        .init(channel: .throttleActual, title: "Actual Throttle Angle", purpose: "Observed throttle response.", diagnosticUse: "Compare against command and controller source states to characterize unexpected closure.", relatedInvestigations: ["Unexpected Throttle Closure"], qualityNote: "Use command/actual pairs and account for normal control intervention."),
        .init(channel: .throttleCommanded, title: "Commanded Throttle Angle", purpose: "Requested throttle state.", diagnosticUse: "Pair with actual angle to derive throttle tracking error.", relatedInvestigations: ["Unexpected Throttle Closure"], qualityNote: "Parameter semantics may differ between pedal request, effective command and blade command."),
        .init(channel: .timingAdvance, title: "Timing Advance", purpose: "Logged spark timing value distinct from knock-retard/spark-source state.", diagnosticUse: "Correlate commanded spark against load, RPM and knock activity to separate base-table timing from retard events.", relatedInvestigations: ["Knock / Spark Retard"], qualityNote: "The channel name \"Timing Advance (SAE)\" was confirmed present in a real user-supplied HP Tuners .hpl export, not synthetic test data; PredatorLab's mapping, units and scaling for this parameter remain unverified assumptions until confirmed against the source controller's definition."),
        .init(channel: .ambientAirTemp, title: "Ambient Air Temperature", purpose: "Outside-air thermal context independent of intake/charge temperature.", diagnosticUse: "Use as a baseline reference when separating ambient conditions from heat-soak or charge-air effects on knock and fueling.", relatedInvestigations: ["Knock / Spark Retard", "R04 Fuel Capability"], qualityNote: "The channel name \"Ambient Air Temp (SAE)\" was confirmed present in a real user-supplied HP Tuners .hpl export, not synthetic test data; PredatorLab's mapping, units and scaling for this parameter remain unverified assumptions until confirmed against the source controller's definition."),
        .init(channel: .barometricPressure, title: "Barometric Pressure", purpose: "Ambient pressure context for load and boost calculations.", diagnosticUse: "Normalize MAP/boost and airflow-derived values against altitude/weather-driven barometric shifts.", relatedInvestigations: ["R04 Fuel Capability"], qualityNote: "The channel name \"Barometric Pressure (SAE)\" was confirmed present in a real user-supplied HP Tuners .hpl export, not synthetic test data; PredatorLab's mapping, units and scaling for this parameter remain unverified assumptions until confirmed against the source controller's definition."),
        .init(channel: .fuelTrimShortTerm1, title: "Short Term Fuel Trim (Bank 1)", purpose: "Closed-loop correction applied in the near term to reach commanded mixture on Bank 1.", diagnosticUse: "Compare against long-term trim and lambda error to separate transient correction from a persistent fueling bias.", relatedInvestigations: ["R04 Fuel Capability", "Lambda Deviation"], qualityNote: "The channel name \"Short Term Fuel Trim Bank 1 (SAE)\" was confirmed present in a real user-supplied HP Tuners .hpl export, not synthetic test data; PredatorLab's mapping, units and scaling for this parameter remain unverified assumptions until confirmed against the source controller's definition."),
        .init(channel: .fuelTrimLongTerm1, title: "Long Term Fuel Trim (Bank 1)", purpose: "Adaptive correction learned over time to reach commanded mixture on Bank 1.", diagnosticUse: "Track drift over a session or across sessions to identify a developing fueling bias distinct from short-term correction.", relatedInvestigations: ["R04 Fuel Capability", "Lambda Deviation"], qualityNote: "The channel name \"Long Term Fuel Trim Bank 1 (SAE)\" was confirmed present in a real user-supplied HP Tuners .hpl export, not synthetic test data; PredatorLab's mapping, units and scaling for this parameter remain unverified assumptions until confirmed against the source controller's definition."),
        .init(channel: .inferredOctane, title: "Inferred Octane", purpose: "Controller-estimated fuel octane derived from knock behavior.", diagnosticUse: "Correlate with knock retard and borderline-knock state to assess whether observed retard tracks a fuel-quality estimate rather than a hardware condition.", relatedInvestigations: ["Knock / Spark Retard"], qualityNote: "The channel name \"Inferred Octane\" was confirmed present in a real user-supplied HP Tuners .hpl export, not synthetic test data; PredatorLab's mapping, units and scaling for this parameter remain unverified assumptions until confirmed against the source controller's definition."),
        .init(channel: .borderlineKnock, title: "Borderline Knock", purpose: "Controller state indicating the engine is operating at or near the knock threshold.", diagnosticUse: "Bound the onset of knock-limited operation and correlate with knock retard, inferred octane and thermal/load context.", relatedInvestigations: ["Knock / Spark Retard"], qualityNote: "The channel name \"Borderline Knock\" was confirmed present in a real user-supplied HP Tuners .hpl export, not synthetic test data; PredatorLab's mapping, units and scaling for this parameter remain unverified assumptions until confirmed against the source controller's definition.")
    ]
}
