import Foundation

/// Domain-neutral hypothesis contract used by every investigation after R04.
/// These are PredatorLab-authored diagnostic reasoning paths until their individual claims are source-verified.
struct AuthoredDiagnosticHypothesis: Identifiable, Codable, Equatable {
    let id: String
    var title: String
    var mechanism: String
    var supportingEvidence: [String]
    var contradictingEvidence: [String]
    var requiredEvidence: [String]
    var nextMeasurements: [String]
    var evidenceBoundary: String
}

enum AuthoredInvestigationLibrary {
    static let pressure: [AuthoredDiagnosticHypothesis] = [
        .init(id:"FP1", title:"Delivery capacity / pressure loss", mechanism:"Actual rail pressure cannot follow commanded pressure as fuel demand rises.", supportingEvidence:["Command-to-actual pressure error grows with load", "Error repeats at similar demand"], contradictingEvidence:["Pressure remains tightly controlled through the symptom"], requiredEvidence:["Fuel pressure command", "Fuel pressure actual", "RPM/load context"], nextMeasurements:["Compare command and actual pressure through onset/recovery", "Capture pump command/duty if available", "Measure electrical supply under load"], evidenceBoundary:"Pressure tracking alone does not identify pump, restriction, wiring, sensor, or control cause."),
        .init(id:"FP2", title:"Pressure measurement / PID identity", mechanism:"The displayed pressure channel may not represent the physical quantity assumed by the investigation.", supportingEvidence:["Pressure behavior conflicts with independent measurements", "Channel semantics are unverified"], contradictingEvidence:["Independent measurement corroborates the scanner channel"], requiredEvidence:["PID definition/source", "Independent pressure measurement"], nextMeasurements:["Verify PID identity", "Correlate with independent gauge/transducer"], evidenceBoundary:"Treat scanner labels as strategy-specific until verified."),
        .init(id:"FP3", title:"Command strategy / controller intervention", mechanism:"The controller intentionally changes pressure target or ownership during the event.", supportingEvidence:["Command changes before actual pressure follows", "Protection/source state changes at onset"], contradictingEvidence:["Command remains stable while actual pressure departs"], requiredEvidence:["Pressure command", "Controller/source state"], nextMeasurements:["Overlay pressure command with source-state transitions"], evidenceBoundary:"A commanded change is not a mechanical pressure failure.")
    ]
    static let lambda: [AuthoredDiagnosticHypothesis] = [
        .init(id:"L1", title:"Fuel-delivery deviation", mechanism:"Measured lambda departs command because delivered fuel does not match demand.", supportingEvidence:["Lambda error follows pressure or injector-margin degradation"], contradictingEvidence:["Fuel delivery evidence remains stable"], requiredEvidence:["Lambda command/measured", "Fuel pressure", "Injector PW margin"], nextMeasurements:["Overlay lambda error with pressure error and PW margin"], evidenceBoundary:"Lambda deviation does not by itself identify the failed component."),
        .init(id:"L2", title:"Transient transport / sensor response", mechanism:"Short command/measured separation reflects exhaust transport or sensor response rather than sustained fueling error.", supportingEvidence:["Brief deviation rapidly recovers", "Deviation follows rapid throttle/shift transient"], contradictingEvidence:["Deviation persists at steady condition"], requiredEvidence:["High-rate lambda command/measured", "Throttle/gear context"], nextMeasurements:["Measure onset and recovery delay under repeatable transient"], evidenceBoundary:"PredatorLab timing classification is derived analysis, not an OEM monitor definition."),
        .init(id:"L3", title:"Sensor / exhaust integrity", mechanism:"Measured lambda is biased by sensor, wiring, heater, or exhaust-path behavior.", supportingEvidence:["Measured value conflicts with independent evidence", "Bank/channel asymmetry where available"], contradictingEvidence:["Independent wideband corroborates scanner value"], requiredEvidence:["Independent lambda/AFR reference", "Sensor electrical evidence"], nextMeasurements:["Correlate with independent wideband", "Inspect sensor/heater/electrical evidence"], evidenceBoundary:"Do not condemn an oxygen sensor from a single PID trace.")
    ]
    static let knock: [AuthoredDiagnosticHypothesis] = [
        .init(id:"K1", title:"Combustion knock / octane sensitivity", mechanism:"Spark intervention follows combustion behavior under load.", supportingEvidence:["Retard repeats in comparable high-load region", "Thermal/fuel context increases susceptibility"], contradictingEvidence:["Retard appears without load relationship"], requiredEvidence:["Knock retard", "RPM/load", "IAT2", "spark source"], nextMeasurements:["Repeat under controlled fuel/thermal condition", "Compare cylinders/banks if channels exist"], evidenceBoundary:"Knock-retard PID is controller response, not direct proof of audible detonation."),
        .init(id:"K2", title:"Thermal sensitivity", mechanism:"Elevated charge/coolant temperature changes knock tendency or spark strategy.", supportingEvidence:["Retard correlates with IAT2/coolant across comparable runs"], contradictingEvidence:["Retard unchanged across materially different thermal states"], requiredEvidence:["IAT1/IAT2", "coolant temperature", "comparable load"], nextMeasurements:["Compare cold versus heat-soaked matched events"], evidenceBoundary:"Correlation with temperature does not isolate calibration from physical combustion effects."),
        .init(id:"K3", title:"Noise / false-knock path", mechanism:"Mechanical or driveline noise is interpreted by the control strategy as knock-like activity.", supportingEvidence:["Retard aligns tightly with shifts/impact events", "Independent combustion evidence does not support knock"], contradictingEvidence:["Retard is load/combustion-repeatable away from mechanical transients"], requiredEvidence:["Shift timing", "knock retard", "spark source", "repeatability"], nextMeasurements:["Correlate retard with DCT/impact events", "Inspect mechanical-noise candidates"], evidenceBoundary:"Requires independent evidence; telemetry alone cannot prove false knock.")
    ]
    static let throttle: [AuthoredDiagnosticHypothesis] = [
        .init(id:"T1", title:"Intentional torque intervention", mechanism:"Actual throttle closes because a controller intentionally reduces delivered torque.", supportingEvidence:["Command or protection/source state changes before closure"], contradictingEvidence:["Command remains open with unexplained actual-position error"], requiredEvidence:["Throttle command/actual", "torque/protection source", "gear"], nextMeasurements:["Align source ownership with throttle command and actual"], evidenceBoundary:"A closed throttle can be commanded behavior, not a throttle-body fault."),
        .init(id:"T2", title:"Throttle actuator / tracking error", mechanism:"Actual throttle fails to follow command.", supportingEvidence:["Sustained command/actual error without matching torque request"], contradictingEvidence:["Actual follows command closely"], requiredEvidence:["Throttle command/actual", "DTC/electrical context"], nextMeasurements:["Quantify tracking error", "Review throttle actuator DTC/electrical evidence"], evidenceBoundary:"Do not infer actuator failure until command semantics and control ownership are verified."),
        .init(id:"T3", title:"Shift-related torque management", mechanism:"Throttle movement is synchronized with DCT torque handoff.", supportingEvidence:["Closure begins within the shift episode and recovers with shift completion"], contradictingEvidence:["Closure occurs far from shift activity"], requiredEvidence:["Gear command/actual", "throttle", "shift timing"], nextMeasurements:["Normalize traces around shift onset"], evidenceBoundary:"Shift correlation does not prove abnormal DCT behavior.")
    ]
    static let dct: [AuthoredDiagnosticHypothesis] = [
        .init(id:"D1", title:"Normal torque handoff", mechanism:"Observed transient is expected controller coordination during gear change.", supportingEvidence:["Repeatable bounded transient with clean recovery", "Command/actual gear sequence is coherent"], contradictingEvidence:["Transient persists after shift completion"], requiredEvidence:["Gear command/actual", "throttle", "protection source"], nextMeasurements:["Compare multiple same-gear shifts under matched load"], evidenceBoundary:"Normal/abnormal classification requires validated reference behavior."),
        .init(id:"D2", title:"Shift execution / clutch transient", mechanism:"Gear execution or torque transfer departs the repeatable baseline.", supportingEvidence:["Shift duration or RPM behavior is an outlier across comparable shifts"], contradictingEvidence:["Shift distribution matches baseline"], requiredEvidence:["RPM", "gear command/actual", "multiple comparable shifts"], nextMeasurements:["Build same-shift duration/RPM distributions", "Capture DCT temperatures if available"], evidenceBoundary:"Scanner telemetry cannot by itself identify a clutch hardware defect."),
        .init(id:"D3", title:"Engine-side intervention during shift", mechanism:"Engine controller protection overlaps the DCT shift and dominates the observed torque reduction.", supportingEvidence:["Protection/source state precedes or overlaps transient"], contradictingEvidence:["No protection ownership appears"], requiredEvidence:["Protection source", "spark source", "gear timing"], nextMeasurements:["Overlay controller-source states around T=0 shift onset"], evidenceBoundary:"Ownership must be established before assigning the symptom to transmission hardware.")
    ]
    static let boost: [AuthoredDiagnosticHypothesis] = [
        .init(id:"B1", title:"Airflow / boost delivery limitation", mechanism:"Observed manifold pressure under-delivers relative to the repeatable comparable baseline.", supportingEvidence:["Pressure deficit repeats at matched RPM/throttle", "Throttle remains open"], contradictingEvidence:["Pressure matches baseline"], requiredEvidence:["MAP/boost", "RPM", "throttle", "IAT2"], nextMeasurements:["Compare matched pressure traces", "Inspect belt/bypass/air-path evidence"], evidenceBoundary:"Pressure deficit alone does not isolate belt slip, bypass, leakage, or calibration."),
        .init(id:"B2", title:"Intentional airflow control", mechanism:"Throttle or bypass/torque strategy intentionally limits manifold pressure.", supportingEvidence:["Pressure change follows command/source intervention"], contradictingEvidence:["Control requests remain unchanged"], requiredEvidence:["Throttle", "protection source", "boost/MAP"], nextMeasurements:["Establish control ownership before mechanical inspection"], evidenceBoundary:"Do not label intentional torque management as boost-system failure."),
        .init(id:"B3", title:"Thermal density / heat-soak effect", mechanism:"Higher charge temperature changes density and observed pressure/airflow behavior.", supportingEvidence:["Difference scales with IAT2 across matched events"], contradictingEvidence:["Large pressure difference remains after thermal matching"], requiredEvidence:["IAT1/IAT2", "MAP/boost", "matched RPM/throttle"], nextMeasurements:["Compare cold and heat-soaked matched cohorts"], evidenceBoundary:"Thermal correlation is not a component diagnosis.")
    ]
    static let thermal: [AuthoredDiagnosticHypothesis] = [
        .init(id:"TH1", title:"Charge-air heat soak", mechanism:"IAT2 rises relative to IAT1 during low-airflow/high-load operation and recovers with airflow.", supportingEvidence:["IAT2-IAT1 delta grows during soak and falls with speed"], contradictingEvidence:["IAT2 does not respond to operating state"], requiredEvidence:["IAT1", "IAT2", "vehicle speed", "RPM"], nextMeasurements:["Trend IAT2-IAT1 delta through soak and recovery"], evidenceBoundary:"Temperature trend alone does not identify intercooler hardware condition."),
        .init(id:"TH2", title:"Cooling-system recovery limitation", mechanism:"Thermal state recovers more slowly than comparable historical runs.", supportingEvidence:["Recovery time is a cohort outlier"], contradictingEvidence:["Recovery distribution matches baseline"], requiredEvidence:["Repeated thermal cycles", "coolant/IAT2", "speed/load"], nextMeasurements:["Measure normalized recovery time across comparable sessions"], evidenceBoundary:"Slow recovery needs physical cooling-system evidence before component replacement."),
        .init(id:"TH3", title:"Sensor plausibility / bias", mechanism:"One thermal signal behaves inconsistently with adjacent physical temperatures.", supportingEvidence:["Implausible offset or response compared with related sensors"], contradictingEvidence:["Independent temperature evidence corroborates channel"], requiredEvidence:["Related temperature channels", "independent measurement if available"], nextMeasurements:["Cross-check thermal sensors and ambient reference"], evidenceBoundary:"A suspicious PID is not proof of a failed sensor.")
    ]
}
