import Foundation

// RevNN here refers to a step in the external "PredatorLab-Expanded-Hardening"
// lineage this project ported from (see HANDOFF.md), NOT this app's own version
// history.
// Status: Independent/standalone.

// Rev73: GT500-specific experiment dossiers. Requirements are evidence contracts, not Ford calibration thresholds.
struct GT500ExperimentDossierRev73: Identifiable, Codable, Hashable {
    enum Domain: String, Codable, CaseIterable { case fuelDelivery, lambdaControl, airflowBoost, sparkKnock, thermal, torqueThrottle, tractionSeparation, trc75Shift }
    let id: String
    let domain: Domain
    let title: String
    let question: String
    let requiredSemantics: [String]
    let optionalSemantics: [String]
    let permittedConclusions: [String]
    let forbiddenConclusions: [String]
    let nextMeasurements: [String]
    let evidenceBoundary: String
}

enum GT500ExperimentDossierCatalogRev73 {
    static let all: [GT500ExperimentDossierRev73] = [
        .init(id:"fuel-reserve",domain:.fuelDelivery,title:"Fuel-Delivery Reserve",question:"Does measured fuel delivery remain repeatable as demand rises?",requiredSemantics:["engine.rpm","driver.pedal","lambda.commanded","lambda.measured"],optionalSemantics:["fuel.pressure","injector.demand","battery.voltage"],permittedConclusions:["Describe commanded/measured lambda deviation and repeatability within the tested envelope.","Identify missing fuel-pressure or injector-demand evidence."],forbiddenConclusions:["Do not invent universal safe fuel-pressure, injector-duty, or horsepower limits.","Do not infer pump capacity from lambda alone."],nextMeasurements:["Reviewed fuel-pressure semantic","Reviewed injector-demand/headroom semantic","Matched repeated pull"],evidenceBoundary:"Fuel reserve is an evidence question. Mechanical capacity and controller limits require applicable source-backed semantics and repeated measurement."),
        .init(id:"lambda-control",domain:.lambdaControl,title:"Lambda-Control Behavior",question:"How closely does measured mixture follow a verified commanded lambda signal?",requiredSemantics:["engine.rpm","lambda.commanded","lambda.measured"],optionalSemantics:["driver.pedal","fuel.pressure","airflow"],permittedConclusions:["Quantify deviation distributions and chronology when both lambda semantics are verified."],forbiddenConclusions:["Do not call a deviation safe/unsafe without an authored, source-backed acceptance contract."],nextMeasurements:["Verify commanded lambda identity","Verify wideband transform/source","Repeat matched stable window"],evidenceBoundary:"Commanded and measured lambda are separate evidence streams; transforms and source provenance remain attached."),
        .init(id:"airflow-boost",domain:.airflowBoost,title:"Airflow / Boost Realization",question:"How do verified airflow, pressure, throttle and demand observations evolve through a pull?",requiredSemantics:["engine.rpm","driver.pedal","throttle"],optionalSemantics:["airflow","boost.pressure","manifold.pressure","charge.temperature"],permittedConclusions:["Describe observed realization patterns and repeatability."],forbiddenConclusions:["Do not invent a Ford boost target or identify a proprietary limiter from correlation."],nextMeasurements:["Reviewed pressure semantic","Reviewed airflow/load semantic","Charge-temperature context"],evidenceBoundary:"Observed pressure/airflow response is not automatically a controller target or compressor-efficiency claim."),
        .init(id:"spark-knock",domain:.sparkKnock,title:"Spark / Knock Chronology",question:"What is the sampled order of spark and knock-related observations?",requiredSemantics:["engine.rpm","spark"],optionalSemantics:["knock","spark.correction","charge.temperature","torque.intervention"],permittedConclusions:["Report first-observed chronology and repeated event fingerprints."],forbiddenConclusions:["Temporal order does not prove knock caused a spark change or reveal the active Ford table."],nextMeasurements:["Reviewed knock semantic","Reviewed spark correction semantic","Higher-quality matched acquisition"],evidenceBoundary:"First-out chronology is evidence, not proof of causation."),
        .init(id:"thermal",domain:.thermal,title:"Thermal / Heat-Soak Behavior",question:"Does vehicle response change consistently as measured thermal state changes?",requiredSemantics:["engine.rpm","driver.pedal"],optionalSemantics:["charge.temperature","coolant.temperature","oil.temperature","dct.temperature","spark","throttle"],permittedConclusions:["Compare repeated cold/warm/hot cohorts and describe associations."],forbiddenConclusions:["Do not invent Ford derate thresholds or protection-table values."],nextMeasurements:["Reviewed IAT2/charge-temperature semantic","Repeated matched pulls","Recovery pull after cooldown"],evidenceBoundary:"Thermal association is not proprietary threshold discovery."),
        .init(id:"torque-throttle",domain:.torqueThrottle,title:"Throttle / Torque Intervention",question:"What verified request, delivered-response and throttle observations change first?",requiredSemantics:["engine.rpm","driver.pedal","throttle"],optionalSemantics:["torque.request","torque.delivered","spark","traction.state","shift.state"],permittedConclusions:["Rank observed intervention chronology when semantics are reviewed."],forbiddenConclusions:["Do not name a proprietary torque limiter solely from a throttle closure."],nextMeasurements:["Reviewed torque request/delivered semantics","Traction/stability state","TR_C75 shift state"],evidenceBoundary:"Torque arbitration remains a hypothesis graph until causal edges have applicable evidence."),
        .init(id:"traction-separation",domain:.tractionSeparation,title:"Traction vs Powertrain Separation",question:"Is intervention evidence more consistent with chassis/traction activity, transmission coordination, powertrain activity, or unresolved?",requiredSemantics:["engine.rpm","driver.pedal"],optionalSemantics:["traction.state","stability.state","wheel.slip","throttle","torque.intervention","shift.state"],permittedConclusions:["Classify support as chassis, transmission, powertrain, mixed, or unresolved."],forbiddenConclusions:["Missing traction semantics must remain unknown; absence of evidence is not evidence of inactivity."],nextMeasurements:["Reviewed traction/stability state","Wheel-speed/slip context","Torque/shift state"],evidenceBoundary:"Classification is evidence support, not a claim about undocumented Ford control ownership."),
        .init(id:"trc75-shift",domain:.trc75Shift,title:"TR_C75 Shift Phases",question:"How repeatable are observed gear-transition phases for the same gear pair, mode, strategy and thermal band?",requiredSemantics:["engine.rpm","transmission.gear"],optionalSemantics:["shift.state","vehicle.speed","longitudinal.acceleration","dct.temperature","torque.request"],permittedConclusions:["Reconstruct pre-shift, transition and recovery timing from observed signals.","Compare repeated same-cohort shift fingerprints."],forbiddenConclusions:["Do not infer clutch pressure, clutch capacity, internal hydraulic command, or durability from RPM behavior alone."],nextMeasurements:["Reviewed shift-state semantic","DCT thermal context","Repeated same-gear cohort"],evidenceBoundary:"TR_C75 observations stay bound to exact TCM strategy and verified channel semantics.")
    ]

    static func dossier(_ domain: GT500ExperimentDossierRev73.Domain) -> GT500ExperimentDossierRev73 { all.first { $0.domain == domain }! }
    static func scannerPlan(for domain: GT500ExperimentDossierRev73.Domain, reviews: [VCMScannerSemanticReview]) -> ScannerContractPlanRev72 {
        let d=dossier(domain); return ScannerContractBuilderRev72.build(requiredSemanticIDs:d.requiredSemantics,reviews:reviews)
    }
}

struct MPVI4FactRev73: Identifiable, Codable, Hashable {
    enum Authority: String, Codable { case hpTunersOfficial, predatorLabInterpretation }
    let id:String; let category:String; let statement:String; let authority:Authority; let sourceLocator:String; let operationalMeaning:String
}

enum MPVI4KnowledgeBaseRev73 {
    static let officialFacts:[MPVI4FactRev73] = [
        .init(id:"cpu",category:"Hardware",statement:"Dual-core 1.7 GHz processor and 1 GB RAM.",authority:.hpTunersOfficial,sourceLocator:"HP Tuners MPVI4 product page",operationalMeaning:"Supports the newer interface architecture and high-speed standalone logging; it does not establish a vehicle-specific PID rate."),
        .init(id:"radio",category:"Connectivity",statement:"Bluetooth 5.2; Wi-Fi 802.11 a/b/g/n up to 150 Mbps is listed as future-firmware functionality on the product page.",authority:.hpTunersOfficial,sourceLocator:"HP Tuners MPVI4 product page",operationalMeaning:"PredatorLab must version capability by firmware/date and must not assume Wi-Fi availability merely because hardware is present."),
        .init(id:"suite",category:"Software",statement:"Works with VCM Suite 5.2+; VCM Scanner 5.2 added MPVI4 support and a newer log format.",authority:.hpTunersOfficial,sourceLocator:"HP Tuners MPVI4 + VCM Scanner documentation",operationalMeaning:"Import provenance should record VCM Suite/Scanner version where known."),
        .init(id:"pro",category:"Features",statement:"Pro Feature Set is standard on MPVI4 and enables standalone data logging and PROLINK+ support.",authority:.hpTunersOfficial,sourceLocator:"HP Tuners MPVI4 / PROLINK+ pages",operationalMeaning:"Standalone logging and external-input provenance belong in the evidence model."),
        .init(id:"prolink",category:"External I/O",statement:"PROLINK+ supports two dedicated 0–5 V analog inputs and one 500 kbps CAN input, with a stated 100 Hz sampling rate.",authority:.hpTunersOfficial,sourceLocator:"HP Tuners PROLINK+ product page",operationalMeaning:"External wideband/MAP/CAN evidence must retain source, transform, units and wiring/configuration provenance."),
        .init(id:"usb",category:"Connectivity",statement:"USB-C is provided; HP Tuners recommends USB to the PC when using VCM Suite.",authority:.hpTunersOfficial,sourceLocator:"MPVI4 User Guide",operationalMeaning:"Treat wired VCM Suite sessions separately from Bluetooth/TDN and standalone sessions."),
        .init(id:"tdn",category:"Mobile",statement:"TDN uses Bluetooth with MPVI4 for mobile workflows.",authority:.hpTunersOfficial,sourceLocator:"MPVI4 User Guide",operationalMeaning:"TDN lineage is a distinct acquisition/remote-tuning workflow, not OEM authority."),
        .init(id:"obdfuse",category:"Electrical",statement:"HP Tuners warns that a 20 A maximum-size fuse is required ahead of the unit.",authority:.hpTunersOfficial,sourceLocator:"MPVI4 Connecting to a Vehicle",operationalMeaning:"Surface this as device-use guidance; vehicle-specific fuse location/rating still comes from applicable vehicle documentation."),
        .init(id:"overvoltage",category:"Protection",statement:"Status LED becomes solid red above 15.5 V and returns to green below 15.5 V; HP Tuners warns operation above 15.5 V can damage the interface.",authority:.hpTunersOfficial,sourceLocator:"MPVI4 Face Plate Description",operationalMeaning:"Capture supply-voltage anomalies when diagnosing interface communication or flash-session problems."),
        .init(id:"overcurrent",category:"Protection",statement:"Firmware attempts bus recovery up to three times after an overcurrent event; persistent overcurrent produces solid red and requires power-cycle or OBD reset recovery.",authority:.hpTunersOfficial,sourceLocator:"MPVI4 Face Plate Description",operationalMeaning:"A red status condition can be interface protection evidence and should not automatically be blamed on VCM software."),
        .init(id:"leds",category:"Human Interface",statement:"Faceplate includes status, BLE and Wi-Fi indicators plus a standalone-data-log/Bluetooth button and USB-C connector.",authority:.hpTunersOfficial,sourceLocator:"MPVI4 Face Plate Description",operationalMeaning:"PredatorLab can provide a state decoder without inferring undocumented internal faults."),
        .init(id:"env",category:"Environment",statement:"Documented operating environment: -20 to 50 °C, 0–2000 m altitude, 10–90% humidity; keep dry and do not immerse.",authority:.hpTunersOfficial,sourceLocator:"MPVI4 Recommended Usage and Cleaning",operationalMeaning:"Environmental context can be retained when interface reliability is under investigation."),
        .init(id:"drivers",category:"Setup",statement:"On Windows 10 or later, MPVI4 is documented as plug-and-play with no manual driver update required.",authority:.hpTunersOfficial,sourceLocator:"Preparing a New Interface Device for Use",operationalMeaning:"Setup troubleshooting should first distinguish device sync/firmware/USB/vehicle communication from manual driver installation."),
        .init(id:"sync",category:"Setup",statement:"HP Tuners documents Help > Resync Interface in VCM Editor for updating/synchronizing the interface.",authority:.hpTunersOfficial,sourceLocator:"Preparing a New Interface Device for Use",operationalMeaning:"Record resync/firmware state when investigating reproducibility or support issues."),
        .init(id:"license",category:"Licensing",statement:"Vehicle licensing is required to write a tune; scanning/logging/diagnostics do not themselves require a vehicle license. Licenses are tied to VIN, module serial number and controller OS per HP Tuners documentation.",authority:.hpTunersOfficial,sourceLocator:"HP Tuners Licenses vs Credits",operationalMeaning:"PredatorLab should distinguish device credits, vehicle license state and calibration evidence."),
        .init(id:"telemetry",category:"Cloud workflow",statement:"VCM Telemetry supports MPVI4 standalone logging, completed-session upload over Wi-Fi/hotspot, browser review and controlled sharing when requirements are met.",authority:.hpTunersOfficial,sourceLocator:"HP Tuners VCM Telemetry",operationalMeaning:"Cloud-uploaded sessions require their own lineage; upload convenience does not alter evidence semantics.")
    ]
    static let boundary="MPVI4 documentation describes interface behavior and workflow. It does not reveal proprietary Ford controller algorithms, guarantee a GT500-specific sample rate, or validate a tune. Firmware-dependent features must be treated as versioned capabilities."
}
