import Foundation

struct GT500ResearchEvidenceRecord: Identifiable, Codable, Equatable {
    enum Authority: String, Codable { case ford = "Ford", fordPerformance = "Ford Performance", nhtsaFord = "Ford via NHTSA", hpTuners = "HP Tuners" }
    let id: String
    let targetID: String
    let authority: Authority
    let title: String
    let locator: String
    let applicability: String
    let supportedFacts: [String]
    let boundary: String
}

enum GT500ResearchEvidenceCatalog {
    static let records: [GT500ResearchEvidenceRecord] = [
        .init(id:"ford.power.2021", targetID:"ford.wiring.production", authority:.ford, title:"2021 Mustang power distribution", locator:"FordServiceContent owner information: fuse/relay table", applicability:"2021 Mustang GT500 where explicitly identified", supportedFacts:["15 A fuel injector circuit","30 A GT500 Fuel Pump #2 circuit","30 A fuel pump circuit","5 A PCM circuit","5 A ABS run/start circuit","5 A EPAS circuit","VDM appears on a protected circuit","GT500 charge-air-cooler pump relay","GT500 differential pump/relay"], boundary:"Power distribution evidence is not a complete connector/pin/cavity wiring diagram."),
        .init(id:"ford.c105.49581", targetID:"ford.wiring.production", authority:.nhtsaFord, title:"SSM 49581 – GT500 transmission concerns / C105", locator:"NHTSA MC-10187985-0001", applicability:"2020–2021 Mustang GT500", supportedFacts:["C105 is an inline connector next to the right-side valve cover","Ford directs inspection for pushed-out terminals, terminal damage and harness damage during transmission concern diagnosis"], boundary:"Does not establish every C105 cavity or circuit assignment."),
        .init(id:"ford.abs.49544", targetID:"ford.abs.epb", authority:.nhtsaFord, title:"SSM 49544 – EPB battery drain / ABS software", locator:"NHTSA MC-10187932-0001", applicability:"2020 Mustang GT500", supportedFacts:["EPB-after-key-off battery drain can be associated with ABS module software","Ford correction is ABS module reprogramming for the affected condition"], boundary:"A software SSM is not complete ABS/EPB wiring or hydraulic diagnostic proof."),
        .init(id:"ford.trc75.212059", targetID:"hpt.trc75.definitions", authority:.nhtsaFord, title:"TSB 21-2059 – P175E/P0874", locator:"NHTSA MC-10189778-0001", applicability:"2020 Mustang GT500", supportedFacts:["P175E/P0874 can be associated with TCM transmission-fluid-pressure-sensor parameters","Ford instructs reading TCM DID 1E1A engine-off","3.0 bar is the decision point stated in this specific TSB procedure","TCM reprogramming is part of the specified repair path when criteria are met"], boundary:"The 3.0 bar value is procedure-specific evidence, not a universal DCT operating-pressure limit."),
        .init(id:"ford.scdrive.50578", targetID:"ford.predator.30301f", authority:.nhtsaFord, title:"SSM 50578 – P1228 supercharger drive", locator:"NHTSA MC-10209027-0001", applicability:"2020–2021 Mustang GT500", supportedFacts:["P1228/lack-of-power can be caused by the supercharger-drive one-way clutch","With belt removed, the failed clutch described by Ford rotates freely in both directions","Drive assembly KR3Z-6J022-B is separately serviceable"], boundary:"This is one documented failure mode, not proof that every P1228 event has this cause."),
        .init(id:"ford.generator.222500", targetID:"ford.sensors.pced", authority:.nhtsaFord, title:"TSB 22-2500 – rough idle / generator current sensor", locator:"NHTSA MC-10230771-0001", applicability:"Certain 2022 Shelby GT500 built on/after 22-Jul-2022", supportedFacts:["A rough idle with no associated DTC can result from an incorrect generator current sensor in the specified build population","Ford procedure calls for inspection/replacement of the generator current sensor"], boundary:"Build-date applicability is mandatory; this is not a generic rough-idle diagnosis."),
        .init(id:"ford.valvecovers.51811", targetID:"ford.predator.30301f", authority:.nhtsaFord, title:"SSM 51811 – valve-cover seal leaks", locator:"NHTSA MC-10239628-0001", applicability:"Certain 2022 GT500 and 2023 Raptor R built on/before 14-May-2023", supportedFacts:["Oil leakage may occur at spark-plug-tube and/or VCT-solenoid seals","Ford directs replacement of both valve-cover assemblies for the specified condition"], boundary:"Shared service evidence does not make Raptor R calibration/controller data transferable to GT500."),
        .init(id:"hpt.channels", targetID:"hpt.scanner.stock", authority:.hpTuners, title:"VCM Scanner Channels", locator:"HP Tuners Docs / VCM Scanner / Channels", applicability:"VCM Scanner acquisition architecture", supportedFacts:["Channel sources include vehicle/OBD, HP Tuners device/external inputs and serial devices","Saved XML channel configs include Parameter ID, source, polling interval and transform","More polled channels can reduce return rate","Broadcast channels avoid polling overhead","External channels do not reduce vehicle polling rate in the same way"], boundary:"Configured polling interval is not proof of actual observed per-channel sample cadence."),
        .init(id:"hpt.support.trc75", targetID:"hpt.trc75.definitions", authority:.hpTuners, title:"Ford supported controllers", locator:"HP Tuners supported vehicles/controllers", applicability:"2020–2022 Shelby GT500 TCM", supportedFacts:["HP Tuners lists Shelby GT500 TCM TR_C75 support for 2020–2022"], boundary:"Controller support does not provide a complete public table/parameter definition corpus."),
        .init(id:"hpt.support.tc298b", targetID:"hpt.tc298b", authority:.hpTuners, title:"Predator Control Pack controller support", locator:"HP Tuners supported vehicles/controllers", applicability:"Ford Performance 5.2L GT500 Predator Control Pack", supportedFacts:["HP Tuners identifies the control-pack PCM as TC-298B"], boundary:"This does not establish that a production 2020–2022 GT500 PCM is the same calibration/application."),
        .init(id:"frpp.m6017m52sc", targetID:"hpt.tc298b", authority:.fordPerformance, title:"M-6017-M52SC GT500 Engine Control Pack", locator:"Ford Performance M-6017-M52SC", applicability:"Ford Performance control-pack installation", supportedFacts:["Uses a production PCM with Ford Performance calibration","Uses a unique control-pack harness","Requires a return-type fuel system","Ford states installing this PCM in a production GT500 causes a no-start"], boundary:"Control-pack wiring, fueling and calibration must remain quarantined from production-GT500 truth."),
        .init(id:"hpt.trackaddict", targetID:"trackaddict.session.schema", authority:.hpTuners, title:"TrackAddict enhanced OBD-II data", locator:"HP Tuners Support: TrackAddict Enhanced OBD-II Data", applicability:"TrackAddict OBD acquisition", supportedFacts:["Current ordinary acquisition is largely limited to manufacturer-exposed SAE Mode 01 parameters","Standard Mode 01 does not define brake, wheel/tire, steering, gear-number or knock data"], boundary:"Do not promise VCM-Scanner-equivalent enhanced GT500 channels in TrackAddict without vehicle-specific evidence."),
        .init(id:"hpt.tdn.write", targetID:"tdn.remote.bundle", authority:.hpTuners, title:"TDN tune delivery/write workflow", locator:"HP Tuners TDN & RTD4 User Guide", applicability:"Supported TDN/RTD workflows", supportedFacts:["Received tuner files can be synchronized and written to the vehicle","Normal Write and Full Write have different semantics","Restore Stock Calibration is controller-dependent and not universally supported"], boundary:"Workflow documentation is not evidence that a particular GT500 flash occurred; preserve per-session lineage."),
    ]

    static func records(for targetID: String) -> [GT500ResearchEvidenceRecord] { records.filter { $0.targetID == targetID } }
}
