import Foundation

/// Narrow, claim-level official-source seeds. These sources verify only the statements explicitly
/// represented below; they do not promote adjacent seed-library content to verified status.
enum OfficialSourceRegistry {
    static let ford2022Supplement = TechnicalSource(title:"2022 Shelby GT500 Mustang Supplement",sourceType:"Ford official owner supplement",reference:"November 2021, First Printing, NR3J 19A285 LAA",grade:.a_factory,confidence:.high,url:"https://www.fordservicecontent.com/Ford_Content/Catalog/owner_information/2022-Ford-Mustang-Shelby-GT500-Supplement-version-1_sg_EN-US_11_2021.pdf",accessMethod:"Public Ford service content",notes:"Owner/supplement authority; not a substitute for Workshop Manual pinpoint tests or wiring information.")
    static let tremecTR9070 = TechnicalSource(title:"TR-9070 Dual-Clutch Transmission",sourceType:"TREMEC official product literature",reference:"TR-9070 original-equipment product literature",grade:.b_professional,confidence:.high,url:"https://tremec.com/products-and-services/conventional-drivetrain/dual-clutch-transmissions/",accessMethod:"Public manufacturer literature",notes:"Manufacturer-level generic TR-9070 architecture/specification source.")
    static let tremecGT500Program = TechnicalSource(title:"TREMEC Introduces New 7-Speed Dual Clutch Transmission",sourceType:"TREMEC official release",reference:"February 25, 2019",grade:.b_professional,confidence:.high,url:"https://tremec.com/tremec-introduces-new-7-speed-dual-clutch-transmission/",accessMethod:"Public manufacturer release",notes:"Supports TR-9070 relationship to Ford Shelby Mustang GT500 program and generic transmission capability statements.")
    static let fordPredatorCrank = TechnicalSource(title:"5.2L GT500 Crankshaft M-6303-M52B",sourceType:"Ford Performance official part page",reference:"M-6303-M52B",grade:.a_factory,confidence:.high,url:"https://performanceparts.ford.com/part/M-6303-M52B",accessMethod:"Public Ford Performance catalog",notes:"Applies only to the exact part/application statements on the page; page states use in 2020–2021 GT500 Predator and 93 mm stroke.")

    static let ford2022OwnerManual = TechnicalSource(title:"2022 Mustang Owner's Manual",sourceType:"Ford official owner manual",reference:"2022 Mustang owner manual, fuse tables",grade:.a_factory,confidence:.high,url:"https://www.fordservicecontent.com/Ford_Content/Catalog/owner_information/2022-Ford-Mustang-Owners-Manual-version-1_om_EN-US_11_2021.pdf",accessMethod:"Public Ford service content",notes:"Owner-manual fuse/protected-component information only; not a wiring diagram or pinpoint test.")
    static let fordTSB222500 = TechnicalSource(title:"TSB 22-2500 — 2022 Mustang Shelby GT500 Rough Idle",sourceType:"Ford Technical Service Bulletin via NHTSA",reference:"TSB 22-2500, 05 January 2023",grade:.a_factory,confidence:.high,url:"https://static.nhtsa.gov/odi/tsbs/2023/MC-10230771-0001.pdf",accessMethod:"Public NHTSA manufacturer communication",notes:"Applies only to the bulletin criteria, including build date and symptom.")
    static let fordGT500ControlPack = TechnicalSource(title:"5.2L Mustang GT500 Engine Control Pack",sourceType:"Ford Performance official part page",reference:"M-6017-M52SC",grade:.a_factory,confidence:.high,url:"https://performanceparts.ford.com/part/M-6017-M52SC",accessMethod:"Public Ford Performance catalog",notes:"Custom-build control-pack architecture; explicitly not the production GT500 body harness and not valid as production GT500 pinout evidence.")
    static let fordSSM49581 = TechnicalSource(title:"SSM 49581 — 2020-2021 Mustang GT500 Transmission Concerns / C105 Inspection",sourceType:"Ford Special Service Message via NHTSA",reference:"SSM 49581",grade:.a_factory,confidence:.high,url:"https://static.nhtsa.gov/odi/tsbs/2021/MC-10187985-0001.pdf",accessMethod:"Public NHTSA manufacturer communication",notes:"Verifies the bulletin-specific C105 inspection context only; not a complete connector pinout or wiring diagram.")
    static let fordSSM49544 = TechnicalSource(title:"SSM 49544 — 2020 Mustang GT500 Battery Drain / ABS Module Software",sourceType:"Ford Special Service Message via NHTSA",reference:"SSM 49544",grade:.a_factory,confidence:.high,url:"https://static.nhtsa.gov/odi/tsbs/2021/MC-10187932-0001.pdf",accessMethod:"Public NHTSA manufacturer communication",notes:"2020 GT500 battery-drain condition after EPB application; software/service-message scope only.")
    static let fordGT500RHHead = TechnicalSource(title:"5.2L Gen 3 RH Cylinder Head",sourceType:"Ford Performance official part page",reference:"M-6049-M52B",grade:.a_factory,confidence:.high,url:"https://performanceparts.ford.com/part/M-6049-M52B",accessMethod:"Public Ford Performance catalog",notes:"Production 2021 GT500 RH cylinder-head part information; not a complete engine rebuild/clearance specification.")

    static let verifiedClaims:[TechnicalClaim] = [
        .init(id:"official.ssm49581.c105",statement:"Ford SSM 49581 directs technicians diagnosing certain 2020-2021 GT500 transmission concerns/DTCs to inspect inline connector C105 next to the right-side valve cover for pushed-out terminals, terminal damage, or harness damage.",value:nil,unit:nil,applicability:"2020-2021 Mustang GT500; SSM 49581 transmission concern/DTC context",source:fordSSM49581,locator:"SSM 49581 service message body",state:.oemVerified,criticality:.diagnostic,downstreamUses:["DCT investigation","electrical topology","connector inspection"],notes:"Does not verify C105 pin count, terminal numbering, conductor colors, electrical role, CAN assignment, or 2022 applicability."),
        .init(id:"official.ssm49544.abs.software",statement:"Ford SSM 49544 states some 2020 GT500 vehicles may exhibit battery drain when the electric parking brake is applied after ignition-off due to ABS module software, with ABS-module reprogramming identified as the correction.",value:nil,unit:nil,applicability:"2020 Mustang GT500; battery drain after EPB application following ignition-off",source:fordSSM49544,locator:"SSM 49544 service message body",state:.oemVerified,criticality:.diagnostic,downstreamUses:["ABS dossier","battery-drain investigation"],notes:"Software-condition evidence only. It does not establish ABS wiring, pinout, general battery-drain causation, or applicability to other model years."),
        .init(id:"official.2022.fuse.gearshift",statement:"Ford lists passenger-compartment fuse 12 as 7.5 A and includes the GT500 gear shift module among its protected components.",value:"7.5",unit:"A",applicability:"2022 Mustang GT500; owner-manual fuse table",source:ford2022OwnerManual,locator:"Fuses — passenger compartment fuse panel, fuse 12",state:.oemVerified,criticality:.descriptive,downstreamUses:["electrical reference","DCT power-supply context"],notes:"Protected-component table only. Does not establish connector pins, wire colors, circuit path, or pinpoint-test procedure."),
        .init(id:"official.2022.fuse.vdm",statement:"Ford lists passenger-compartment fuse 24 as 30 A for the vehicle dynamics module.",value:"30",unit:"A",applicability:"2022 Mustang; owner-manual fuse table",source:ford2022OwnerManual,locator:"Fuses — passenger compartment fuse panel, fuse 24",state:.oemVerified,criticality:.descriptive,downstreamUses:["vehicle dynamics reference"],notes:"Does not by itself establish GT500 MagneRide wiring or diagnostic procedure."),
        .init(id:"official.2022.oilfilter.housing.torque",statement:"Ford's 2022 GT500 supplement specifies 22–26 N·m (16–19 lb-ft) for installation of the oil filter housing after installing a new filter element.",value:"22-26",unit:"N·m",applicability:"2022 Shelby GT500 oil-filter service described in supplement",source:ford2022Supplement,locator:"Maintenance — engine oil/filter procedure",state:.oemVerified,criticality:.service,downstreamUses:["maintenance procedure"],notes:"Exact supplement procedure scope only."),
        .init(id:"official.2022.tsb.generator.sensor",statement:"Ford TSB 22-2500 states that some 2022 Shelby GT500 vehicles built on or after 22-Jul-2022 may have rough idle with no DTC due to an incorrect generator current sensor.",value:nil,unit:nil,applicability:"2022 Shelby GT500 built on/after 22-Jul-2022 with rough idle and no associated DTC",source:fordTSB222500,locator:"Issue/Action criteria",state:.oemVerified,criticality:.diagnostic,downstreamUses:["rough-idle investigation","electrical sensor dossier"],notes:"Do not generalize to earlier builds or rough-idle cases with different symptoms/evidence."),
        .init(id:"official.controlpack.returnfuel",statement:"Ford Performance states M-6017-M52SC uses a Ford Performance-calibrated PCM requiring a return-type fuel system and that installing this PCM in a production GT500 Mustang results in a no-start condition.",value:nil,unit:nil,applicability:"Ford Performance M-6017-M52SC custom-build control pack",source:fordGT500ControlPack,locator:"Part overview",state:.oemVerified,criticality:.descriptive,downstreamUses:["modification applicability","fuel-system reference"],notes:"This is explicit evidence that the control-pack harness/calibration must not be treated as production-GT500 wiring/calibration truth."),
        .init(id:"official.2021.head.valves",statement:"Ford Performance lists the production 2021 GT500 RH cylinder head M-6049-M52B with 38.3 mm intake valves and 32.5 mm exhaust valves.",value:"38.3 / 32.5",unit:"mm",applicability:"M-6049-M52B production 2021 GT500 RH cylinder head",source:fordGT500RHHead,locator:"Part overview",state:.oemVerified,criticality:.descriptive,downstreamUses:["engine dossier"],notes:"Valve dimensions are not piston-to-valve, bearing, ring-gap, or other engine rebuild clearances."),
        .init(id:"official.2022.supplement",statement:"Ford published a 2022 Shelby GT500 Mustang Supplement specific to the vehicle.",value:nil,unit:nil,applicability:"2022 Shelby GT500",source:ford2022Supplement,locator:"Cover/introduction",state:.oemVerified,criticality:.descriptive,downstreamUses:["vehicle applicability","reference provenance"],notes:"Does not verify workshop procedures or scanner semantics."),
        .init(id:"official.tr9070.capacity",statement:"TREMEC publishes the TR-9070 as a 7-speed dual-clutch transmission with 900 Nm torque capacity and shift transitions under one tenth of a second.",value:"900",unit:"Nm",applicability:"Generic TR-9070 product specification",source:tremecTR9070,locator:"TR-9070 product description",state:.manufacturerVerified,criticality:.descriptive,downstreamUses:["DCT dossier"],notes:"Generic manufacturer specification, not a GT500 diagnostic threshold."),
        .init(id:"official.tr9070.gt500",statement:"TREMEC states that the TR-9070 program was developed in connection with Ford's Shelby Mustang GT500 program.",value:nil,unit:nil,applicability:"TR-9070 / Shelby Mustang GT500 program",source:tremecGT500Program,locator:"2019 official release",state:.manufacturerVerified,criticality:.descriptive,downstreamUses:["DCT dossier","vehicle applicability"],notes:nil),
        .init(id:"official.predator.crank.stroke",statement:"Ford Performance lists M-6303-M52B as used in the 2020–2021 GT500 760-hp Predator engine and specifies a 93 mm stroke.",value:"93",unit:"mm",applicability:"M-6303-M52B; Ford Performance page explicitly says 2020–2021 GT500 Predator",source:fordPredatorCrank,locator:"Part details",state:.oemVerified,criticality:.descriptive,downstreamUses:["engine dossier"],notes:"Do not silently extend the page's model-year statement to 2022 without a separate source."),
        .init(id:"official.2022.suspension.front.layout",statement:"Ford lists the 2022 GT500 front suspension as MacPherson strut, double ball-joint.",value:"MacPherson strut, double ball-joint",unit:nil,applicability:"2022 Shelby GT500 and 2022 Shelby GT500 Carbon Fiber Track Pack",source:ford2022Supplement,locator:"Technical Specifications — Suspension",state:.oemVerified,criticality:.descriptive,downstreamUses:["suspension dossier"],notes:"Owner supplement specification; not a workshop diagnostic procedure."),
        .init(id:"official.2022.suspension.rear.layout",statement:"Ford lists the 2022 GT500 rear suspension as multi-link.",value:"Multi-link",unit:nil,applicability:"2022 Shelby GT500 and 2022 Shelby GT500 Carbon Fiber Track Pack",source:ford2022Supplement,locator:"Technical Specifications — Suspension",state:.oemVerified,criticality:.descriptive,downstreamUses:["suspension dossier"],notes:nil),
        .init(id:"official.2022.suspension.front.spring.base",statement:"Ford specifies a 44 N/mm (251 lbf/in) front spring rate for the 2022 GT500 without the Carbon Fiber Track Pack.",value:"44",unit:"N/mm",applicability:"2022 Shelby GT500, base/non-CFTP specification",source:ford2022Supplement,locator:"Technical Specifications — Suspension",state:.oemVerified,criticality:.descriptive,downstreamUses:["suspension dossier"],notes:"Variant-specific. Do not apply to Carbon Fiber Track Pack."),
        .init(id:"official.2022.suspension.front.spring.cftp",statement:"Ford specifies a 47 N/mm (268 lbf/in) front spring rate for the 2022 GT500 Carbon Fiber Track Pack.",value:"47",unit:"N/mm",applicability:"2022 Shelby GT500 Carbon Fiber Track Pack",source:ford2022Supplement,locator:"Technical Specifications — Suspension",state:.oemVerified,criticality:.descriptive,downstreamUses:["suspension dossier"],notes:"Variant-specific."),
        .init(id:"official.2022.suspension.rear.spring.base",statement:"Ford specifies a 155 N/mm (885 lbf/in) rear spring rate for the 2022 GT500 without the Carbon Fiber Track Pack.",value:"155",unit:"N/mm",applicability:"2022 Shelby GT500, base/non-CFTP specification",source:ford2022Supplement,locator:"Technical Specifications — Suspension",state:.oemVerified,criticality:.descriptive,downstreamUses:["suspension dossier"],notes:"Variant-specific. Do not apply to Carbon Fiber Track Pack."),
        .init(id:"official.2022.suspension.rear.spring.cftp",statement:"Ford specifies a 165 N/mm (942 lbf/in) rear spring rate for the 2022 GT500 Carbon Fiber Track Pack.",value:"165",unit:"N/mm",applicability:"2022 Shelby GT500 Carbon Fiber Track Pack",source:ford2022Supplement,locator:"Technical Specifications — Suspension",state:.oemVerified,criticality:.descriptive,downstreamUses:["suspension dossier"],notes:"Variant-specific."),
        .init(id:"official.2022.suspension.front.stabilizer",statement:"Ford specifies a 36 mm diameter x 4.8 mm wall front stabilizer bar for both the 2022 GT500 and 2022 GT500 Carbon Fiber Track Pack.",value:"36 x 4.8",unit:"mm diameter x mm wall",applicability:"2022 Shelby GT500 and 2022 Shelby GT500 Carbon Fiber Track Pack",source:ford2022Supplement,locator:"Technical Specifications — Suspension",state:.oemVerified,criticality:.descriptive,downstreamUses:["suspension dossier"],notes:"Variant table reports the same front bar specification for both configurations."),
        .init(id:"official.2022.suspension.rear.stabilizer.base",statement:"Ford specifies a 24 mm diameter x 3.6 mm wall rear stabilizer bar for the 2022 GT500 without the Carbon Fiber Track Pack.",value:"24 x 3.6",unit:"mm diameter x mm wall",applicability:"2022 Shelby GT500, base/non-CFTP specification",source:ford2022Supplement,locator:"Technical Specifications — Suspension",state:.oemVerified,criticality:.descriptive,downstreamUses:["suspension dossier"],notes:"Variant-specific. Do not apply to Carbon Fiber Track Pack."),
        .init(id:"official.2022.suspension.rear.stabilizer.cftp",statement:"Ford specifies a 25.4 mm diameter x 4.5 mm wall rear stabilizer bar for the 2022 GT500 Carbon Fiber Track Pack.",value:"25.4 x 4.5",unit:"mm diameter x mm wall",applicability:"2022 Shelby GT500 Carbon Fiber Track Pack",source:ford2022Supplement,locator:"Technical Specifications — Suspension",state:.oemVerified,criticality:.descriptive,downstreamUses:["suspension dossier"],notes:"Variant-specific."),
        .init(id:"official.tr9070.gt500.output",statement:"TREMEC describes the Shelby GT500 application as pairing a 760-horsepower 5.2-liter V8 and 625 lb-ft of torque with the TR-9070 7-speed DCT.",value:"625",unit:"lb-ft",applicability:"Shelby GT500 / TR-9070 program description",source:tremecGT500Program,locator:"Official GT500/TR-9070 program material",state:.manufacturerVerified,criticality:.descriptive,downstreamUses:["DCT dossier","vehicle reference"],notes:"Manufacturer program description; not a diagnostic limit, durability threshold, or calibration target.")
    ]
}
