import XCTest
@testable import PredatorLab
final class Rev133ExecutionTests:XCTestCase {
 func testDirectPointLowerBound(){let p=(0..<100).map{TelemetryPointRev116(time:Double($0),value:Double($0))};XCTAssertEqual(TelemetryHotPathRev116.lowerBound(points:p,target:50.5),51)}
 func testEnvelopePreservesExtrema(){let p=[TelemetryPointRev116(time:0,value:0),.init(time:1,value:99),.init(time:2,value:-4)];let e=TelemetryHotPathRev116.envelopes(p,bucketSize:3)[0];XCTAssertEqual(e.maximum,99);XCTAssertEqual(e.minimum,-4)}
 func testWindowEnvelopeBound(){let p=(0..<1000).map{TelemetryPointRev116(time:Double($0),value:Double($0%17))};let w=ForensicTimelineEngineRev117.window(series:[.init(id:"x",points:p)],start:0,end:1000,cursor:1,pixelWidth:100);XCTAssertLessThanOrEqual(w.envelopes["x"]!.count,100)}
 func testContextEvidenceDoesNotSupport(){let e=StructuredForensicEvidenceRev131(id:"1",sourceArtifactSHA256:"h",episodeID:"e",hypothesisID:"H",channel:"RPM",timestamp:0,numericValue:1,stringValue:nil,units:"rpm",authority:.measuredExported,relation:.context,derivation:nil,boundary:"x");let x=StructuredHypothesisEvidenceEngineRev133.assess(hypothesisNames:["H"],evidence:[e])[0];XCTAssertEqual(x.netEvidence,0)}
 func testContradictionPenaltyExceedsSupport(){let a=StructuredForensicEvidenceRev131(id:"a",sourceArtifactSHA256:"h",episodeID:"e",hypothesisID:"H",channel:"A",timestamp:0,numericValue:1,stringValue:nil,units:"",authority:.measuredExported,relation:.supports,derivation:nil,boundary:"x");let b=StructuredForensicEvidenceRev131(id:"b",sourceArtifactSHA256:"h",episodeID:"e",hypothesisID:"H",channel:"B",timestamp:0,numericValue:1,stringValue:nil,units:"",authority:.measuredExported,relation:.contradicts,derivation:nil,boundary:"x");XCTAssertLessThan(StructuredHypothesisEvidenceEngineRev133.assess(hypothesisNames:["H"],evidence:[a,b])[0].netEvidence,0)}
 func testBaselineRejectsUnknown(){var r=BaselineRegistryRev133();let b=BaselineDesignationRev132(id:"x",vehicleID:UUID(),buildStateID:nil,sourceSHA256:nil,sourceFilename:"x",designatedAt:.now,authority:.unknown,configurationNote:"",validationNote:"",boundary:"");XCTAssertThrowsError(try r.add(b))}
 func testPhysicalLedgerNeedsHash(){var l=PhysicalValidationLedgerRev133();l.record(.init(id:"x",stage:.repeatability,sourceSHA256:nil,configurationID:"c",observedAt:.now,observation:"",evidenceFiles:[],authority:"observed",boundary:""));XCTAssertFalse(l.stageComplete(.repeatability))}
 func testBenchmarkPlanIncludesFiveMillion(){XCTAssertTrue(PerformanceBenchmarkPlanRev133.cases.contains{$0.points==5_000_000})}
}
