import XCTest
@testable import PredatorLab
final class Rev131EvidenceCapabilityTests:XCTestCase {
 func testDefaultThresholdsAreAnalysisParameters(){let t=GT500EpisodeThresholdSetRev131.analysisDefaults;XCTAssertTrue(t.usable);XCTAssertEqual(t.highDemandPedal.source,.analysisParameter);XCTAssertTrue(t.highDemandPedal.authorityBoundary.contains("not a Ford WOT"));XCTAssertTrue(t.thermalIAT2Context.authorityBoundary.contains("not a GT500 protection"))}
 func testUnknownThresholdSetRefusesSegmentation(){let x=DetectionThresholdRev131(value:1,units:"x",source:.unknown,rationale:"",authorityBoundary:"");let t=GT500EpisodeThresholdSetRev131(highDemandPedal:x,highDemandThrottle:x,throttleDifference:x,accelerationRPMDelta:x,episodeMergeGap:x,thermalIAT2Context:x);XCTAssertFalse(t.usable)}
 func testSep2LikeChannelsBlockDCTClaims(){let m=ForensicCapabilityMapperRev131.map(channels:["Engine RPM (SAE)","Accelerator Position D (SAE)","Throttle Angle","Fuel Pressure (SAE)","Intake Air Temp 2"]);XCTAssertEqual(m.capabilities.first{$0.id=="dctSlip"}?.state,.blocked);XCTAssertEqual(m.capabilities.first{$0.id=="shiftPhase"}?.state,.blocked)}
 func testThrottleCapabilityRequiresActualArtifactChannels(){let m=ForensicCapabilityMapperRev131.map(channels:["Accelerator Position D (SAE)","Throttle Desired Angle","Throttle Angle"]);XCTAssertEqual(m.capabilities.first{$0.id=="throttle"}?.state,.available)}
 func testStructuredEvidenceIsContextNotAutomaticSupport(){let log=ParsedLogData(filename:"x",fileURL:nil,channels:["Engine RPM (SAE)"],timestamps:[1],samples:[["Engine RPM (SAE)":1000.0]],duration:0,sampleCount:1);let e=GT500EpisodeRev122(id:"e",kind:.highDemand,start:1,end:1,peakTime:1,observations:1,evidence:[],boundary:"");let s=[TimelineSeriesRev117(id:"Engine RPM (SAE)",points:[.init(time:1,value:1000)])];let r=StructuredEvidenceBuilderRev131.cursorRecords(log:log,sourceSHA256:"abc",episode:e,cursor:1,series:s,units:["Engine RPM (SAE)":"rpm"]);XCTAssertEqual(r.first?.relation,.context);XCTAssertEqual(r.first?.sourceArtifactSHA256,"abc");XCTAssertTrue(r.first?.boundary.contains("not causal support") == true)}
}
