import SwiftUI

// RevNN here refers to a step in the external "PredatorLab-Expanded-Hardening"
// lineage this project ported from (see HANDOFF.md), NOT this app's own version
// history.
// Status: Independent/standalone.
struct MPVI4DiagnosticAcquisitionLabRev74View:View {
 @State private var mode:MPVI4ConnectionModeRev74 = .standalone
 @State private var state=MPVI4ConnectionStateRev74()
 var assessment:MPVI4WorkflowAssessmentRev74 { MPVI4ConnectionStateMachineRev74.assess(mode,state) }
 var body:some View { List {
  Section("Connection State Machine") { Picker("Workflow",selection:$mode){ForEach(MPVI4ConnectionModeRev74.allCases,id:\.self){Text($0.rawValue).tag($0)}}; Toggle("OBD/interface power confirmed",isOn:$state.obdPower); Toggle("USB connected",isOn:$state.usb); Toggle("Bluetooth/TDN connected",isOn:$state.bluetooth); Toggle("Scanner config reviewed",isOn:$state.scannerConfigured); Toggle("Standalone config deployed",isOn:$state.standaloneConfigured); Toggle("Wi-Fi/hotspot path confirmed",isOn:$state.wifi); Toggle("Firmware current",isOn:$state.firmwareCurrent); Label(assessment.ready ? "Workflow ready" : "Blocked",systemImage:assessment.ready ? "checkmark.shield":"exclamationmark.triangle"); ForEach(assessment.blockers,id:\.self){Text($0).font(.caption)} }
  Section("Executable tools") { NavigationLink("LED + Protection Decoder"){MPVI4LEDLabRev74View()}; NavigationLink("VCM Telemetry Lineage"){VCMTelemetryLabRev74View()}; NavigationLink("PROLINK+ Channel Builder"){PROLINKLabRev74View()}; NavigationLink("Acquisition Benchmark Protocol"){AcquisitionBenchmarkRev74View()} }
  Section("Digital-twin health map") { Text("MPVI4 → GT500 controller → Scanner semantic → acquisition quality → experiment → evidence. A green interface is not automatically a green evidence chain.").font(.caption).foregroundStyle(.secondary) }
 }.navigationTitle("MPVI4 Acquisition Lab") }
}
private struct MPVI4LEDLabRev74View:View { var body:some View { List { Section("Documented protection clues"){ForEach(MPVI4LEDDecoderRev74.known){x in VStack(alignment:.leading){Text(x.meaning);ForEach(x.nextChecks,id:\.self){Text("• \($0)").font(.caption)};Text(x.authority).font(.caption2).foregroundStyle(.secondary)}}}; Section("Rule"){Text("LED state is evidence. Never infer a unique root cause where HP Tuners documents multiple possible states.")}}.navigationTitle("LED Decoder") } }
private struct VCMTelemetryLabRev74View:View { let r=VCMTelemetryEngineRev74.readiness(interfaceCompatible:true,scannerCurrent:false,firmwareCurrent:false,standaloneConfigured:true,internetPath:true,accountReady:false); var body:some View { List { Section("Official workflow"){Text("Configure in supported VCM Scanner → record standalone → connect MPVI4 to Wi-Fi/mobile hotspot → completed session uploads → browser review/compare/share.")}; Section("Readiness example"){ForEach(r.blockers,id:\.self){Text($0)}}; Section("Evidence lineage"){Text("Preserve interface, firmware, Scanner version, experiment, record time, upload state, remote session identifier and share state. Cloud transport does not change channel semantics or validate the tune.").font(.caption)}}.navigationTitle("VCM Telemetry") } }
private struct PROLINKLabRev74View:View { let c=PROLINKChannelRev74(id:"wideband",kind:.analog0to5V,sourceDevice:"External wideband",rawUnits:"V",outputSemantic:"lambda.measured",outputUnits:"lambda",transform:nil,wiringNote:nil); var body:some View { List { Section("PROLINK+ contract"){Text("2 × 0–5 V analog inputs + 1 × 500 kbps CAN input; official product material states 100 Hz sampling.");ForEach(PROLINKChannelBuilderRev74.validate(c),id:\.self){Text($0)}}; Section("Wideband verification"){Text("Record the exact device, wiring, ground/reference arrangement, voltage range, transform, output units and at least two source-backed calibration points before admitting measured lambda.").font(.caption)}}.navigationTitle("PROLINK+ Builder") } }
private struct AcquisitionBenchmarkRev74View:View { var body:some View { List { Section("Protocol"){Text("1. Freeze controller/interface/firmware/VCM version.\n2. Freeze Scanner XML and channel sources.\n3. Record a controlled duration.\n4. Count actual samples and missing values.\n5. Repeat.\n6. Change one channel-contract variable at a time.\n7. Compare observed distributions, not marketing maxima.")}; Section("Boundary"){Text("MPVI4 standalone performance may be described by HP Tuners as on par with VCM Scanner, but PredatorLab will only report measured rates for the exact tested configuration.").font(.caption)}}.navigationTitle("Acquisition Benchmark") } }
